spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: demo
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    schemas: demo